### PR TITLE
renders images

### PR DESCRIPTION
**Pull request by mikesea**
this certainly isn't the best way to render images, but it works. 

the renderImages method just scans through the page everytime a message is posted and will convert images to images. The better approach would simply be to check each message as it's posted, but that was being a pain in the butt. I'll let you guys decide.

### CODE REVIEW

**Comment by mikesea** [comment]
the regex appears to be matching with normal urls, which is not good

trying to find stricter regex

**Comment by mikesea** [comment]
closing lol

**Comment by travisvalentine** [comment]
NOOOOOO

**Comment by nisargshah100** [comment]
We needed this PR! Now we cant render images anymore :(

**Comment by mikesea** [comment]
sorry guys you had your chance

**Pull request closed without merging**
