### PR TITLE
Core usernames

### PR DESCRIPTION
**Pull request by mikesea**
Now returning usernames in Messages api calls, and displaying them when you chat. 

I'll let Dan be the one to merge this in since I added a new column to the core db. I made sure to fix failing tests as well :)

### CODE REVIEW

**Comment by dkaufman** [comment]
Hey, was talking to Travis about this on Thursday, but it didn't occur to me until now that I never circled back with Mike on it. Basically, my thought on returning the username is that it is incorrect from from a service architecture standpoint to have core return the username with the request. If Bouncer is the service that holds information about users, it should be the one to return username.

I can think of 3 different ways for Vaudeville to get the username associated with a particular message:

1) The current implementation, where core is storing the username. I'm pretty uncomfortable with this solution, mainly because that means we are storing the same username in 2 separate databases (core and bouncer), and would need to worry about synching that information together.

2) When Vaudeville requests a message, core returns a json response with the username. However, instead of storing the username in the database, it gets the username from Bouncer on each request. This means that we only store it in one place, and core basically relays the username information over to Vaudeville. I'm a little more comfortable with this solution, as we are not duplicating database info.

3) The "rightest" way, which is for core to only send SID back to Vaudeville, and then Vaudeville makes a followup call to Bouncer for the username. I say that this is the rightest way because each service is taking responsibility for its own information, even though it involves an extra call from Vaudeville.

My vote would ultimately be for Solution 3, if possible. That said, I don't know how difficult this is from a Spine point of view. Maybe DRB makes it easy? If that is going to be too onerous, I would still prefer to go with the Solution 2 over the first one. It would look identical from Spine's point of view, but gets rid of the database duplication.

Sorry for being such a Debbie Downer, definitely let me know if I'm missing anything. Thoughts?

**Comment by nisargshah100** [comment]
I think the best way is for core to make a batch request to the bouncer api to fetch the usernames. When vaudeville makes a request to core, it is expecting a username to be returned. (or any other client for that matter). The frontend shouldn't need to make a separate request with SID to get the username (sid is an internal concept). I feel that its the responsibility of the core to return all the information. The core should internally utilize the SID to batch request from bouncer. 

I will write a function is bouncer which has:
get_users_by_sid(array of sid)

Then you can use sid to request all the users. It needs to be a batch request since making a tons of calls via api / drb is a bad idea.

**Comment by dkaufman** [comment]
Are you saying that it would make this batch request just when /messages is called, or it would do it regularly and save username in its database? The former seems ok, the latter seems dangerous.

**Comment by nisargshah100** [comment]
Former

On Sat, Jun 9, 2012 at 4:59 PM, Daniel Kaufman <
reply@reply.github.com

**Comment by nisargshah100** [comment]
Im gonna go build the sid part into auth. With that - you can hook into it and get the user information. We may want to pass more then just the username, etc.

**Comment by dkaufman** [comment]
Ok, so just to summarize the plan, from what I understand:

When Vaudeville makes a rooms/1/messages call to Core:
    Core will make 2 calls to Bouncer:
       get_user to verify the token of the request
       get_users_by_id(array) to get all of the usernames for the messages
    It will then return a json of each message, including username, to Vaudeville

To achieve this, Nisarg is going to build a get_users_by_id method on Bouncer that return (for now) an array of usernames. 
**Actually, can we name this get_usernames_by_sid, and change it later if necessary?**

I'm going to merge in Mike's pull request, then remove the two files that add username as a column to the core database. Then I'll add in the call to the bouncer method, and the response will not change from mike's perspective.

Let me know if this all does/doesn't make sense.

**Comment by nisargshah100** [comment]
Yep that works fine. I just build a get_users_by_sid which takes in a set of sids and returns the user objects to you which contain the username. You can change that method / create a new method - whichever makes more sense :D

**Comment by mikesea** [comment]
sounds like a plan gang

**Comment by travisvalentine** [comment]
Sorry for just seeing this (and for not relaying to Mike our conversation, Dan). But it looks like everything's squared away so that's cool.

**Pull request closed without merging**
